# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	mkdir -p obj/lib-common
	ar r $(FLOAT) $(FLOAT_OBJ)
	$(CC) -m32 -fno-builtin FLOAT.c

# TODO: write a rule for generating $(FLOAT_OBJ)
