# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

$(FLOAT_OBJ):%.o:$(LIB_COMMON_DIR)/FLOAT.c $(LIB_COMMON_DIR)/FLOAT.h
	mkdir -p obj/lib-common
	$(CC) -m32 -fno-builtin -c $< -o $@
